uvmf:
  environments:
    decode:
      agents:
       - initiator_responder: INITIATOR
         name: din_agent
         type: decode_in
       - initiator_responder: INITIATOR
         name: dout_agent
         type: decode_out
      analysis_components:
       - name: pred
         parameters: []
         type: decode_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'False'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
       - name: d_scbd
         sb_type: uvmf_in_order_scoreboard
         trans_type: decode_out_transaction
      subenvs: []
      tlm_connections:
       - driver: din_agent.monitored_ap
         receiver: pred.analysis_export
       - driver: pred.pred_out_dec
         receiver: d_scbd.expected_analysis_export
       - driver: dout_agent.monitored_ap
         receiver: d_scbd.actual_analysis_export
      imports:
       - name: lc3_prediction_pkg
